### ISSUE TITLE
Java CBOR deserialization error

### ISSUE THREAD

**Issue by daltonj** [TREMA-UNH/trec-car-tools#11]
edu.unh.cs.treccar.playground.ExtractPlainText ".../paragraphcorpus/paragraphcorpus.cbor"

Exception in thread "main" java.lang.ClassCastException: co.nstant.in.cbor.model.UnsignedInteger cannot be cast to co.nstant.in.cbor.model.UnicodeString
	at edu.unh.cs.treccar.read_data.TrecCarHeader.<init>(TrecCarHeader.java:46)
	at edu.unh.cs.treccar.read_data.CborListWithHeaderIterator.<init>(CborListWithHeaderIterator.java:23)
	at edu.unh.cs.treccar.read_data.DeserializeData$1PageIterator.<init>(DeserializeData.java:21)
	at edu.unh.cs.treccar.read_data.DeserializeData.iterAnnotations(DeserializeData.java:29)
	at edu.unh.cs.treccar.read_data.DeserializeData$1.iterator(DeserializeData.java:36)
	at edu.unh.cs.treccar.playground.ExtractPlainText.main(ExtractPlainText.java:53)

I'm using the 1.5 tools branch and the paragraph data from the website.

**Comment by bgamari** [comment]
daltonj <notifications@github.com> writes:

> edu.unh.cs.treccar.playground.ExtractPlainText ".../paragraphcorpus/paragraphcorpus.cbor"
>
> Exception in thread "main" java.lang.ClassCastException: co.nstant.in.cbor.model.UnsignedInteger cannot be cast to co.nstant.in.cbor.model.UnicodeString
> 	at edu.unh.cs.treccar.read_data.TrecCarHeader.<init>(TrecCarHeader.java:46)
> 	at edu.unh.cs.treccar.read_data.CborListWithHeaderIterator.<init>(CborListWithHeaderIterator.java:23)
> 	at edu.unh.cs.treccar.read_data.DeserializeData$1PageIterator.<init>(DeserializeData.java:21)
> 	at edu.unh.cs.treccar.read_data.DeserializeData.iterAnnotations(DeserializeData.java:29)
> 	at edu.unh.cs.treccar.read_data.DeserializeData$1.iterator(DeserializeData.java:36)
> 	at edu.unh.cs.treccar.playground.ExtractPlainText.main(ExtractPlainText.java:53)
>
> I'm using the 1.5 tools branch and the paragraph data from the website.

This is a regression introduced by a format change we introduced for
the next TREC run. Unfortunately it looks like the fallback path isn't
quite right. Fix coming.

**Comment by daltonj** [comment]
Thanks for the quick reply! I've tried both v1.5 and the latest from head and both seem to have the issue.

**Comment by bgamari** [comment]
daltonj <notifications@github.com> writes:

> Thanks for the quick reply! I've tried both v1.5 and the latest from head and both seem to have the issue.
>
Indeed; it is quite concerning that this sort of regression snuck into
`v1.5`. I'm setting up some CI as we speak to ensure this doesn't happen
again.
