### ISSUE TITLE
issue with reading TREC data by using trec-car-tools in python3

### ISSUE THREAD

**Issue by XueSiyuan1217** [TREMA-UNH/trec-car-tools#16]
I have already followed the instruction to access the data  by test.py, but there is something wrong I can not figure it out.

Here are the problem I met:

[xuesiyuan@241server python3]$ python ./trec_car/read_data.py ./benchmarkY1/benchmarkY1-train/train.pages.cbor ./benchmarkY1/benchmarkY1-train/train.pages.cbor-outlines.cbor ./benchmarkY1/benchmarkY1-train/train.pages.cbor-paragraphs.cbor  >out

After this, there is nothing out.

[xuesiyuan@241server python3]$ python read_data_test.py ./benchmarkY1/benchmarkY1-train/train.pages.cbor ./benchmarkY1/benchmarkY1-train/train.pages.cbor-outlines.cbor  ./benchmarkY1/benchmarkY1-train/train.pages.cbor-paragraphs.cbor >out
Traceback (most recent call last):
  File "read_data_test.py", line 14, in <module>
    for p in iter_annotations(f):
  File "/home/xuesiyuan/pythonworkspace/pythonWorkspace/py3/trec-car-tools-1.5/python3/trec_car/read_data.py", line 509, in _iter_with_header
    yield parse(cbor.load(file))
  File "/home/xuesiyuan/pythonworkspace/pythonWorkspace/py3/trec-car-tools-1.5/python3/trec_car/read_data.py", line 71, in from_cbor
    return Page(pagename, pageId, map(PageSkeleton.from_cbor, cbor[3]), PageMetadata.from_cbor(cbor[4]))
  File "/home/xuesiyuan/pythonworkspace/pythonWorkspace/py3/trec-car-tools-1.5/python3/trec_car/read_data.py", line 215, in from_cbor
    pageType=PageType.from_cbor(cbor[1])
IndexError: list index out of range

Is there anything wrong ??

**Comment by laura-dietz** [comment]
The code is fixed, but it not yet on anaconda cloud.

Here is how to install:
1) activate your python environment
2) clone this repository
3) cd python3
4) call `python setup.py install`
5) use it!  (You can test it by calling python read_data_test.py)
