### ISSUE TITLE
ClassCastException in DeserializeData.java 

### ISSUE THREAD

**Issue by lweiland** [TREMA-UNH/trec-car-tools#5]
Exception in thread "main" java.lang.ClassCastException: co.nstant.in.cbor.model.ByteString cannot be cast to co.nstant.in.cbor.model.UnicodeString
	at edu.unh.cs.treccar.read_data.DeserializeData.pageFromCbor(DeserializeData.java:157)
	at edu.unh.cs.treccar.read_data.DeserializeData$1.lowLevelNext(DeserializeData.java:36)
	at edu.unh.cs.treccar.read_data.DeserializeData$1.<init>(DeserializeData.java:27)
	at edu.unh.cs.treccar.read_data.DeserializeData.iterAnnotations(DeserializeData.java:26)
	at edu.unh.cs.treccar.read_data.DeserializeData$2.iterator(DeserializeData.java:67)
	at edu.unh.cs.treccar.playground.LinksWithContextKeywords.main(LinksWithContextKeywords.java:157)

As input I'm using release-v1.1.cbor.paragraphs. I guess, I need the complete article.cbor for linksWithContextKeywords, which is mentioned in another issue: enwiki-20161220-pages-articles24.xml-p030503454p033952815.cbor ? 

Thanks for your help

**Comment by laura-dietz** [comment]
Solved in v1.4
